image: gradle:7.3.1-jdk11

variables:
  JACOCO_CSV_LOCATION: '$CI_PROJECT_DIR/build/jacocoCsv'

stages:
  - build
  - test
  - visualize
  # - deploy

build:
  stage: build
  script: 
    # - gradle wrapper
    - chmod +x gradlew
    - ./gradlew clean build
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 day
  # only:
    # - main
  tags: 
    - first

test:
  stage: test
  script: 
    # - gradle wrapper
    - chmod +x gradlew
    - ./gradlew test jacocoTestReport
  artifacts:
    paths:
      - build/reports/jacoco/test/html/index.xml    
  tags: 
    - first
