image: gradle:7.3.1-jdk11

variables:
  JACOCO_CSV_LOCATION: '$CI_PROJECT_DIR/build/jacocoCsv'

stages:
  - build
  - test
  - deploy

job-build:
  stage: build
  script: 
    - chmod +x gradlew
    - ./gradlew clean build
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 day
  # only:
    # - main
  tags: 
    - first

job-test:
  stage: test
  script: 
    - chmod +x gradlew
    - ./gradlew test
    # - ./gradlew test jacocoTestReport
  # artifacts:
  #   paths:
  #     - build/reports/jacoco/test/html/index.xml    
  tags: 
    - first

job-deploy:
  stage: deploy
  script:
    - echo 'Not used'
  tags: 
    - first # gir-runner 이름
