image: gradle:7.3.1-jdk11

stages:
  - build
  - test
  - deploy

job-build:
  stage: build
  script: 
    - chmod +x gradlew
    - ./gradlew clean build -x test
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 day
  # only:
    # - main
  tags: 
    - first

job-test:
  stage: test
  script: 
    - chmod +x gradlew
    - ./gradlew clean test
  tags: 
    - first

job-deploy:
  stage: deploy
  script:
    - echo 'Not used'
  tags: 
    - first # gir-runner 이름
  only:
    - main
