image: openjdk:11

stages:
  - build
  - test
  - visualize
  # - deploy

build:
  stage: build
  script: 
    # - gradle wrapper
    - chmod +x gradlew
    - ./gradlew clean build
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 day
  # only:
    # - main
  tags: 
    - first

# test:
#   stage: test
#   script: 
#     # - gradle wrapper
#     - chmod +x gradlew
#     - ./gradlew test
#   tags: 
#     - first
test:
  stage: test
  script:
    - './gradlew test jacocoTestReport' # jacoco must be configured to create an xml report
  artifacts:
    paths:
      - build/jacoco/jacoco.xml
