
stages:
  - build
  - test
  # - deploy

build:
  image: openjdk:11
  stage: build
  script: 
    - chmod +x gradlew
    - ./gradlew clean build
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 day
  only:
    - main
  # tags: 
    # - first

test:
  stage: test
  script: 
    - ./gradlew test
  # tags: 
  #   - first