
image: java:11-jdk

stages:
  - build
  - test
  # - deploy
cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script: ./gradlew clean build
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 day
  only:
    - main
  tags: 
    - first

test:
  stage: test
  script: ./gradlew test
  # tags: 
  #   - first