image: openjdk:11

stages:
  - build
  - test
  # - deploy

build:
  stage: build
  script: 
    # - gradle wrapper
    - chmod +x gradlew
    - ./gradlew clean build
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 day
  only:
    - main
  tags: 
    - first

test:
  stage: test
  script: 
    # - gradle wrapper
    - chmod +x gradlew
    - ./gradlew test
  tags: 
    - first