version: '3.8'

services:
  mariadb:
    container_name: mariadb
    image: mariadb:10.8.3
    restart: always
    # 환경에 따라 변경
    ports:
      - 3306:3306
    volumes:
      # DB 데이터 저장 디렉토리
      - ./data:/var/lib/mysql
      # 설정 파일 저장될 위칭
      - ./config:/etc/mysql/conf.d
    environment:
      - "MYSQL_ROOT_PASSWORD=rotkfrn196"
      - "TZ=UTC"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
