spring:
  datasource:
    url: jdbc:postgresql://ec2-54-243-92-68.compute-1.amazonaws.com:5432/ddba7rifc027ge
    username: xzctysdcvskklg
    password: ${JDBC_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
#    hibernate:
#      ddl-auto:
#    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: info
    org.spring.framework.web: info
    org.hibernate.SQL: debug
    org.kenux.miraclelibrary: debug
