spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/h2dbs/miracle-library
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: info
    org.spring.framework.web: info
    org.kenux.miraclelibrary: debug
