---
spring:
  config:
    activate:
      on-profile: prd
---
spring:
  config:
    activate:
      on-profile: local-maria
  datasource:
    url: jdbc:mariadb://localhost:3306/miracle_library
    username: kenux
    password: rotkfrn
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    #    show-sql: true
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    properties:
      hibernate:
        format_sql: true
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/h2dbs/miracle-library
    username: sa
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    #    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.H2Dialect

logging:
  level:
    root: info
    org.spring.framework.web: info
    org.hibernate.SQL: debug
    org.kenux.miraclelibrary: debug

#logging:
#  level:
#    org:
#      hibernate:
#        type:
#          descriptor:
#            sql: trace
