spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/miracle_library
    username: kenux
    password: rotkfrn
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
#    show-sql: true
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: info
    org.spring.framework.web: info
    org.hibernate.SQL: debug
    org.kenux.miraclelibrary: debug
